"""Appointment method

Revision ID: 318daf362417
Revises: d0c30ec152ef
Create Date: 2024-01-09 11:16:50.868909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318daf362417'
down_revision = 'd0c30ec152ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
