"""Class methods

Revision ID: d0c30ec152ef
Revises: 2fc7f21b25fc
Create Date: 2024-01-09 11:15:44.653035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c30ec152ef'
down_revision = '2fc7f21b25fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
